name: test

on:
  push:

jobs:
  test:
    name: Test
    runs-on: windows-latest
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     version: ["3.5.0", "3.6.0", "3.8.0"]
    steps:
      - uses: actions/checkout@v2
      - run: npm ci

      - name: Install LuaRocks
        uses: actions/github-script@v5
        # env:
        #   LUAROCKS_VERSION: ${{ matrix.version }}
        with:
          script: |
            const script = require('./install_luarocks.js')
            await script(core)

      - run: luarocks --version

      - run: luarocks config

      - run: luarocks make --verbose

      - name: luarocks make (show --no-verbose result)
        run: luarocks make
        if: always()

      - run: something 1 2
